<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('category')->default('news');
            $table->text('excerpt')->nullable();
            $table->longText('body');

            // 'human' or 'ai'. Kept as its own column rather than inferred from
            // a null author: an admin may edit an AI draft before publishing,
            // and the disclosure on the public page must survive that edit.
            $table->string('source')->default('human');
            $table->string('ai_model')->nullable();

            $table->string('status')->default('draft');
            $table->timestamp('published_at')->nullable();

            // Nullable: an AI post generated by the scheduler has no author,
            // and deleting a staff account must not delete their articles.
            $table->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete();

            $table->string('meta_description', 320)->nullable();
            $table->string('og_image', 500)->nullable();
            $table->boolean('is_featured')->default(false);
            $table->unsignedInteger('views')->default(0);
            $table->timestamps();

            // The public index is always "published, newest first".
            $table->index(['status', 'published_at']);
            $table->index('category');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('posts');
    }
};
