<?php

namespace App\Http\Controllers;

use App\Models\Prediction;
use App\Models\Setting;
use App\Support\MarketRegistry;
use Illuminate\Http\Request;

class PredictionController extends Controller
{
    /** Ranked picks visible without a subscription, per list. */
    public const DEFAULT_FREE_PICKS = 3;

    public function topPicks(Request $request, ?string $market = null)
    {
        $requestedMarket = $market ?? $request->query('market');
        $market = MarketRegistry::resolve($requestedMarket);
        $definition = MarketRegistry::find($market);

        $seoTitles = [
            'win' => 'Top 10 Match Winner Football Predictions — AI Picks Today',
            'over_2_5' => 'Top 10 Over 2.5 Goals Predictions & xG Tips Today',
            'gg' => 'Top 10 Both Teams To Score (BTTS / GG) Predictions Today',
            'fh_over_0_5' => 'Top 10 First Half Over 0.5 Goals Football Predictions',
            'ht_win' => 'Top 10 Half Time Winning (HT 1X2) Predictions & AI Tips',
            'corners_over_8_5' => 'Top 10 Over 8.5 Match Corners Predictions & Stats',
            'cards_over_2_5' => 'Top 10 Over 2.5 Yellow Cards Predictions & Booking Tips',
        ];

        $seoDescriptions = [
            'win' => 'Discover today’s top 10 highest-conviction match winner predictions generated by Poisson expected goals (xG) modeling and audited algorithms.',
            'over_2_5' => 'Explore today’s top 10 Over 2.5 Goals football betting predictions with mathematical xG probability ratings and team form analysis.',
            'gg' => 'High-conviction Both Teams To Score (GG / BTTS) football predictions calculated from offensive/defensive scoring rates across top leagues.',
            'fh_over_0_5' => 'Top 10 First Half Over 0.5 Goals predictions for early-action match fixtures backed by first-half Poisson matrix modeling.',
            'ht_win' => 'Top 10 Leading At Half Time predictions and tactical previews for upcoming European and domestic league fixtures.',
            'corners_over_8_5' => 'Statistically modeled Over 8.5 Corners predictions based on team corner rates and negative binomial league distributions.',
            'cards_over_2_5' => 'Top 10 Over 2.5 Yellow Cards match predictions derived from official referee discipline data and booking averages.',
        ];

        $aiTop5 = Prediction::with(['match.homeClub', 'match.awayClub'])
            ->where('is_ai5', true)
            ->forUpcomingMatches()
            ->orderBy('probability', 'desc')
            ->take(5)
            ->get();

        if ($aiTop5->isEmpty()) {
            (new \App\Jobs\Ai5SelectionJob)->handle();

            $aiTop5 = Prediction::with(['match.homeClub', 'match.awayClub'])
                ->where('is_ai5', true)
                ->forUpcomingMatches()
                ->orderBy('probability', 'desc')
                ->take(5)
                ->get();
        }

        // A market the engine does not produce yet has no picks to fetch; the
        // view renders it as pending rather than as an empty leaderboard.
        $top10Picks = $definition?->generated
            ? Prediction::with('match')
                ->where('market', $market)
                ->forUpcomingMatches()
                ->orderBy('probability', 'desc')
                ->take(10)
                ->get()
            : collect();

        $user = $request->user();
        $isSubscriber = $user ? $user->isSubscriber() : false;

        $canonicalUrl = route('top.picks', ['market' => $market]);

        return view('predictions.top-picks', [
            'market' => $market,
            'definition' => $definition,
            'markets' => MarketRegistry::listed(),
            'aiTop5' => $aiTop5,
            'top10Picks' => $top10Picks,
            'isSubscriber' => $isSubscriber,
            'freePicks' => self::freePicks(),
            'seoTitle' => $seoTitles[$market] ?? ($definition?->label . ' Predictions — GUARANTEED CORRECT'),
            'seoDescription' => $seoDescriptions[$market] ?? "AI-ranked top 10 predictions for {$definition?->label}.",
            'canonicalUrl' => $canonicalUrl,
        ]);
    }

    /**
     * Tunable without a deploy, and clamped: a stray settings value must not be
     * able to unlock the whole list or hide it entirely.
     */
    public static function freePicks(): int
    {
        $configured = (int) Setting::get('free_pick_limit', self::DEFAULT_FREE_PICKS);

        return max(1, min(10, $configured ?: self::DEFAULT_FREE_PICKS));
    }
}
